Repository sem5640-2018/glados, pull requests merged in 2018-11, with the labels that each got.

#10 Add logging to syslog over log4j
  pom.xml
  src/main/resources/log4j2.xml
  src/test/java/LogDataTest.java
Labels: enhancement

#11 Add swagger documentation
  docs/swagger.json
  docs/swagger.yml
Labels: enhancement

#17 Update travis workflow
  .travis.yml
  bin/docker.sh
Labels: enhancement

#19 Push to glados instead of gatekeeper image
  bin/docker.sh
Labels: bug

#18 Ensure PMD runs before unit testing
  .travis.yml
  glados.iml
  pom.xml
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/api/JsonParseExceptionWrapper.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/AuditData.java
Labels: bug

#23 Dockerise build
  .travis.yml
  Dockerfile
  bin/syslog-ng.conf
  glados.iml
  pom.xml
  src/main/resources/log4j2.xml
Labels: bug, enhancement

#25 Add persistence layer and finally get image deployment working
  Dockerfile
  README.md
  bin/syslog-ng.conf
  glados.iml
  pom.xml
  src/main/java/entities/AuditData.java
  src/main/java/entities/AuditDataJson.java
  src/main/java/entities/GsonTimeDeserialiser.java
  src/main/java/exceptions/ExceptionMapper.java
  src/main/java/exceptions/IoExceptionWrapper.java
  src/main/java/exceptions/JsonParseExceptionWrapper.java
  src/main/java/persistence/DatabaseConnection.java
  src/main/java/rest/AuditApi.java
  src/main/java/rest/JAXRSConfiguration.java
  src/main/java/rest/ServiceApi.java
  src/main/java/rest/helpers/ServiceNames.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/api/JAXRSConfiguration.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/AuditDataNoSerial.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/DatabaseConnection.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/IDatabaseConnection.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/LoggingLevels.java
  src/main/java/uk/ac/aber/dcs/aberfitness/glados/db/package-info.java
  src/main/resources/log4j2.xml
  src/main/webapp/WEB-INF/beans.xml
  src/main/webapp/WEB-INF/faces-config.xml
  src/main/webapp/WEB-INF/glassfish-web.xml
  src/main/webapp/WEB-INF/persistence.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/index.xhtml
  src/test/java/UnitTest/AuditApiTest.java
  src/test/java/UnitTest/AuditDataJsonTest.java
  src/test/java/UnitTest/AuditDataTest.java
  src/test/java/helpers/AuditDataHelpers.java
Labels: bug, enhancement

#26 Fixup app errors with deployment
  Dockerfile
  bin/syslog-ng.conf
  glados.iml
  pom.xml
  src/main/java/entities/AuditData.java
  src/main/java/persistence/DatabaseConnection.java
  src/main/java/rest/AuditApi.java
  src/main/resources/META-INF/beans.xml
  src/main/resources/META-INF/persistence.xml
  src/main/webapp/WEB-INF/beans.xml
  src/main/webapp/WEB-INF/glassfish-resources.xml
  src/main/webapp/WEB-INF/glassfish-web.xml
  src/main/webapp/WEB-INF/web.xml
  src/test/java/UnitTest/AuditDataJsonTest.java
Labels: bug, enhancement
